# Form implementation generated from reading ui file 'C:\Users\nesto\OneDrive - Universidad de la Sabana\Universidad\2023-1\Proga avanzada\Presentacion tercer corte\Votacion\Votacion.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 221, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\nesto\\OneDrive - Universidad de la Sabana\\Universidad\\2023-1\\Proga avanzada\\Presentacion tercer corte\\Votacion\\download.jpeg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 221, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\nesto\\OneDrive - Universidad de la Sabana\\Universidad\\2023-1\\Proga avanzada\\Presentacion tercer corte\\Votacion\\images.jpeg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 40, 221, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\nesto\\OneDrive - Universidad de la Sabana\\Universidad\\2023-1\\Proga avanzada\\Presentacion tercer corte\\Votacion\\download (1).jpeg"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 283, 111, 20))
        self.label_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 290, 111, 20))
        self.label_5.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 280, 111, 20))
        self.label_6.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.PBtoro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBtoro.setGeometry(QtCore.QRect(90, 330, 75, 23))
        self.PBtoro.setObjectName("PBtoro")
        self.PBpuma = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBpuma.setGeometry(QtCore.QRect(340, 330, 75, 23))
        self.PBpuma.setObjectName("PBpuma")
        self.PBardilla = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBardilla.setGeometry(QtCore.QRect(610, 330, 75, 23))
        self.PBardilla.setObjectName("PBardilla")
        self.PBF = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PBF.setGeometry(QtCore.QRect(114, 400, 501, 23))
        self.PBF.setObjectName("PBF")
        self.SBV = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.SBV.setGeometry(QtCore.QRect(250, 440, 121, 41))
        self.SBV.setAutoFillBackground(False)
        self.SBV.setReadOnly(True)
        self.SBV.setMaximum(1000000000)
        self.SBV.setObjectName("SBV")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 442, 111, 31))
        self.label_7.setObjectName("label_7")
        self.LTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.LTitulo.setGeometry(QtCore.QRect(-40, 0, 971, 31))
        self.LTitulo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Bruiser"))
        self.label_5.setText(_translate("MainWindow", "Bernie"))
        self.label_6.setText(_translate("MainWindow", "Jack"))
        self.PBtoro.setText(_translate("MainWindow", "Votar"))
        self.PBpuma.setText(_translate("MainWindow", "Votar"))
        self.PBardilla.setText(_translate("MainWindow", "Votar"))
        self.PBF.setText(_translate("MainWindow", "FINALIZAR VOTACION"))
        self.label_7.setText(_translate("MainWindow", "Numeros de votacion"))
        self.LTitulo.setText(_translate("MainWindow", "Votacion para mascota universitaria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
