# Form implementation generated from reading ui file 'C:\Users\nesto\OneDrive - Universidad de la Sabana\Universidad\2023-1\Proga avanzada\Presentacion tercer corte\2 AdmonFacultad\Diseno\DAgregarFuentes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 307)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 431, 172))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ContactoFuente = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ContactoFuente.setObjectName("ContactoFuente")
        self.gridLayout.addWidget(self.ContactoFuente, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.LTitulo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.LTitulo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.gridLayout.addWidget(self.LTitulo, 0, 0, 1, 3)
        self.SBCodigoEliminar = QtWidgets.QSpinBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SBCodigoEliminar.setFont(font)
        self.SBCodigoEliminar.setMaximum(999999999)
        self.SBCodigoEliminar.setObjectName("SBCodigoEliminar")
        self.gridLayout.addWidget(self.SBCodigoEliminar, 1, 1, 1, 1)
        self.NombreFuente = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.NombreFuente.setObjectName("NombreFuente")
        self.gridLayout.addWidget(self.NombreFuente, 3, 1, 1, 1)
        self.PBAgregar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBAgregar.setObjectName("PBAgregar")
        self.gridLayout.addWidget(self.PBAgregar, 5, 1, 1, 1)
        self.PBSalir = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBSalir.setObjectName("PBSalir")
        self.gridLayout.addWidget(self.PBSalir, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Nombre de la Fuente"))
        self.label.setText(_translate("MainWindow", "Codigo Nuevo"))
        self.label_3.setText(_translate("MainWindow", "Contacto"))
        self.LTitulo.setText(_translate("MainWindow", "Agregar Fuentes"))
        self.PBAgregar.setText(_translate("MainWindow", "Agregar Fuente"))
        self.PBSalir.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
